In [2]:
import numpy as np

# Statistiques d’engagement

In [3]:
#Reply Matrix
reply = np.array([[1,5,5,0,0], [2,0,5,0,3], [0,0,0,0,0], [2,0,0,4,0], [0,4,2,0,0]])
reply

array([[1, 5, 5, 0, 0],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [4]:
#Retweet Matrix
retweet = np.array([[0,2,4,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,4,3], [0,2,5,0,0]])
retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 4, 3],
       [0, 2, 5, 0, 0]])

In [5]:
#Like Matrix
like = np.array([[2,5,1,0,3], [0,0,0,0,0], [0,5,0,3,3], [1,0,0,4,1], [0,0,9,0,0]])
like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

In [6]:
#Indice de l’utilisateur qui répond (Reply) plus que les autres
sumReply = reply.sum(axis=1)
np.argmax(sumReply)

0

In [7]:
#Indice de l’utilisateur qui répond (Retweet) plus que les autres
sumRetweet = retweet.sum(axis=1)
np.argmax(sumRetweet)

3

In [43]:
#Indice des les utilisateurs qui ne répondent pas (Reply) et qui ne partagent pas (Retweet)
sum_Reply_Retweet = sumReply + sumRetweet
np.argwhere(sum_Reply_Retweet == 0)

array([[2]], dtype=int64)

In [9]:
#le nombre des Likes que chaque utilisateur fait pour ses propres tweets
selfLikes=like.diagonal()
selfLikes

array([2, 0, 0, 4, 0])

In [10]:
#le nombre des Likes que chaque utilisateur fait pour les tweets autre que les tien
sumLike = like.sum(axis=1)
othersLikes =sumLike- selfLikes
othersLikes

array([ 9,  0, 11,  2,  9])

In [11]:
# Les utilisateurs qui aiment leurs propres tweets plus qu’ils aiment les tweets des autres
likers=np.argwhere(selfLikes>othersLikes)
likers

array([[3]], dtype=int64)

In [12]:
# Calculer leur nombre
nb = np.shape(likers)[0]
nb

1

In [13]:
#le nombre des interactions que chaque utilisateur a fait
sumInteractions = sumReply + sumRetweet + sumLike
sumInteractions

array([28, 10, 11, 19, 22])

# Statistiques sur les interactions

In [113]:
#le max des Likes que chaque utilisateur a reçu
maxLikes = np.max(like, axis=0)
maxLikes

array([2, 5, 9, 4, 3])

In [114]:
# le nombre des arcs entrants (ayant au moins une interaction)
sumMatrix=reply+retweet+like
isInteract = sumMatrix > 0
isInteractBin = isInteract.astype(int)
nbInteractE = isInteractBin.sum(axis=1)
np.argwhere(nbInteractE > 0)

array([[0],
       [1],
       [2],
       [3],
       [4]], dtype=int64)

In [115]:
#nombre des arcs sortants (qui ont fait au moins une interaction)
nbInteractS = isInteractBin.sum(axis=0)
np.argwhere(nbInteractS > 0)


array([[0],
       [1],
       [2],
       [3],
       [4]], dtype=int64)

In [116]:
#les nœuds où le nombre des arcs entrants est égale au nombre de ceux sortants
np.argwhere(nbInteractS == nbInteractE)

array([[1],
       [2]], dtype=int64)

In [117]:
# les Likes qu’ils ont fait entre eux
interLike = like + like.T - np.diag(like.diagonal())
interLike

array([[ 2,  5,  1,  1,  3],
       [ 5,  0,  5,  0,  0],
       [ 1,  5,  0,  3, 12],
       [ 1,  0,  3,  4,  1],
       [ 3,  0, 12,  1,  0]])

#Popularité

In [119]:
#like sans diagonale
likeSDiag = like - np.diag(like.diagonal())
likeSDiag

array([[0, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 0, 1],
       [0, 0, 9, 0, 0]])

In [120]:
#reply sans diagonale
replySDiag = reply - np.diag(reply.diagonal())
replySDiag
        
        

array([[0, 5, 5, 0, 0],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 4, 2, 0, 0]])

In [121]:
#retweet sans diagonale
retweetSDiag = retweet- np.diag(retweet.diagonal())
retweetSDiag

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3],
       [0, 2, 5, 0, 0]])

In [122]:
#transforme reply
replyTrans1 = np.where(replySDiag > likeSDiag, replySDiag* -0.5, replySDiag)
replyTrans2 = np.where(replyTrans1 == 0, 0 , replyTrans1 )
replyTrans2

array([[ 0. ,  5. , -2.5,  0. ,  0. ],
       [-1. ,  0. , -2.5,  0. , -1.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [-1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -2. ,  2. ,  0. ,  0. ]])

In [123]:
#transforme retweet
retweetTrans = retweetSDiag 
retweetTrans

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3],
       [0, 2, 5, 0, 0]])

In [124]:
#transforme like
InterLikes = np.where(InterLikes > 0.5 * InterTweet, InterLikes * 1.5, InterLikes)
InterLikes

array([[ 0.  , 11.25,  1.  ,  0.  ,  6.75],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , 11.25,  0.  ,  6.75,  6.75],
       [ 2.25,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  , 20.25,  0.  ,  0.  ]])